FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# GoSLB

Lightweight load balancer

## Service collection [/services/]

### List all services [GET]

+ Response 200 (application/json)

        [
            "foo.goslb.",
            "bar.goslb."
        ]

### Create a New Service [POST]

Create a new service with specified domain, health monitor and list of endpoints.
The service domain must be a sub-domain of configured service zone (`goslb.` by 
default).

+ Request (application/json)

        {
            "Domain": "foo.goslb.",
            "Endpoints": [
                {
                    "IP": "127.0.0.1", 
                    "Enabled": true,
                    "Priority": 0,
                    "Site": "ie1"
                },
                {
                    "IP": "172.31.1.31",
                    "Enabled": true,
                    "Priority": 0,
                    "Site": "ie2"
                }
            ],
            "Monitor": {
                "Type": "TCP",
                "Interval": 10,
                "Timeout": 2,
                "Port": 80
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /services/foo.goslb.

    + Body

            {
                "Success":true
            }

# Service [/services]